// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  // @ts-ignore
  tutorialSidebar: [
    {
      type: 'html',
      value: 'Get started',
      className: 'sidebar-getting-started', // custom CSS class
      defaultStyle: true, // makes it styled like a sidebar heading
    },
    {
      type: 'doc',       // simple nav item
      label: 'Introduction',     // the text shown in the sidebar
      id: 'intro',        // the doc id this links to
    },
    {
      type: 'doc',
      label: 'Quickstart',
      id: 'quickstart',
    },
    {
      type: 'doc',
      label: 'Glossary',
      id: 'glossary',
    },
   {
      type: 'html',
      value: 'Models',
      className: 'sidebar-getting-started', // custom CSS class
      defaultStyle: true, // makes it styled like a sidebar heading
    }, 
    {
      type: 'doc',
      label: 'Usage guide',
      id: 'models',
    },
    {
      type: 'doc',
      label: 'Classification tutorial',
      id: 'classification',
    },  
    {
      type: 'html',
      value: 'Expert AI Modules',
      className: 'sidebar-getting-started', // custom CSS class
      defaultStyle: true, // makes it styled like a sidebar heading
    },
    {
      type: 'doc',
      label: 'Overview',
      id: 'expert-modules',
    },
    {
      type: 'doc',
      label: 'Core concepts',
      id: 'core_concepts',
    },
    {
      type: 'doc',
      label: 'Categorization module',
      id: 'plot_categorization',
    },
   {
      type: 'doc',
      label: 'Classification module',
      id: 'plot_two_moon_classification',
    },
    // {
    //   type: 'category',
    //   label: 'Quickstart',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],



  
};

export default sidebars;
